spring:
  application:
    name: country-counter
  main:
    banner-mode: off
  redis:
    host: redis
    port: 6379
    lettuce:
      pool:
        min-idle: 10
        max-idle: 10
        max-active: 10
server:
  jetty:
    threads:
      min: 20
      max: 20
